name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install lib gtk
        run: sudo apt install -y libgtk2.0-0

      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Gradle build
        run: ./gradlew build

      - name: Package bootJar
        if: ${{ github.event_name != 'pull_request' }}
        run: ./gradlew bootJar

      - name: Login to the DockerHub registry
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to the Container registry
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          images: |
            ghcr.io/chenqiaoanying/jav-service
            cqay/jav-service
          tags: |
            latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}